apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storage
provisioner: platformer.cloud/nfs # this can be any name, but make sure it's the same name passed onto the nfs-client deployment as well.
parameters:
  archiveOnDelete: "false"
