kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage" # name should be equal to the storage class name we created
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
